# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  image_name: ang
  image_tag: latest

trigger:
- main

pool: 
  name: Default
  

steps:

- script: |
    cd contact-frontend
    npm install -g @angular/cli
    npm install
    ng build 
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    command: 'build'
    repository: $(image_name)
    tags: $(image_tag)
    Dockerfile: '**/Dockerfile'

- script: 
    trivy image $(image_name):$(image_tag)
#- script: 
#    cd contact-frontend
