# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: 
  name: Default
  

steps:

- script: |
    cd contact-frontend
    npm install -g @angular/cli
    npm install
    ng build 
  displayName: 'npm install and build'
  
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub Conn'
    repository: 'alkaifkhan/dockerscannedimages'
    command: 'buildAndPush'
    Dockerfile: 'contact-frontend/Dockerfile'

#- script: 
#    cd contact-frontend
